# This is a basic workflow to help you get started with Actions

name: Build Aplication

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_wrapper:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

  build:
    name: Build app
    needs: check_wrapper
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      
      - name: gradlew chmod to executable
        run: chmod +x ./gradlew

      - name: Build app
        uses: eskatos/gradle-command-action@v2
        with:
          arguments: assembleRelease
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true

      - name: Sign APK with keystore
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KS_TEXT }}
          alias: ${{ secrets.KS_ALIAS }}
          keyStorePassword: ${{ secrets.KS_PSWD }}
          keyPassword: ${{ secrets.KS_PSWD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"

      - name: Upload release APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

      - name: Echo APK
        run: echo Signed APK FILE ${{steps.sign_app.outputs.signedReleaseFile}}

